---
title: "Support Vector Machine KDD dataset"
author: "MarkSniper94"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load subset of dataset.
```{r }
library(e1071)
library(caret)
kdd_prediction <- read.csv("kdd_prediction.csv")
```

Cross validations method.
```{r }
#cross validation 70% train 30% test
percentage = round(nrow(kdd_prediction) *70/100)
cat('There are ', percentage, 'necessary to divide KDD dataset in train (70%) in test (30%).')
max <- nrow(kdd_prediction)
train <- kdd_prediction[ (1:percentage), ]
test <- kdd_prediction[ (percentage:nrow(kdd_prediction)), ]
```

Turn on profilng.
```{r }
Rprof()
```

Fit SVM.
```{r }
fit_svm <- svm(factor(result) ~.,data = train, scale=FALSE)
svm.fitted = predict(fit_svm)
```

Prediction.
```{r }
svm_predict = predict(fit_svm,newdata = test)
```

Turn off profiling.
```{r }
Rprof(NULL) 
```

Get and show profiling information.
```{r }
prof<-summaryRprof()
prof$by.total
```

Show confusion matrix.
```{r }
confusionMatrix(factor(svm_predict), factor(test$result), mode = "everything")
```

Show Roc Curve information.
```{r}
library(pROC)
predictions <- as.numeric(as.numeric(factor(svm_predict)),as.numeric(test$result))
roc.multi <- multiclass.roc(test$result, predictions)
print(roc.multi)
rs <- roc.multi[['rocs']]
plot.roc(rs[[1]])
sapply(2:length(rs),function(i) lines.roc(rs[[i]],col=i))
auc(roc.multi)
print(roc.multi[['rocs']])
```

